### ISSUE TITLE
hello guys I have a problem I am using react js the issue is given in comment help me

### ISSUE THREAD

**Issue by tysepa** [commanderx16/x16-emulator#74]
const postSchema = Schema({
                   ^

ReferenceError: Schema is not defined
    at Object.<anonymous> (C:\Users\student\Desktop\epa\stud\app.js:4:20)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by mist64** [comment]
You want stackoverflow.com
